[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_ENV = "production"
  SCALERMAX_API_URL = "https://api.scalermax.com"

[context.development]
  command = "npm run dev"
  publish = "dist"

  [context.development.environment]
    NODE_ENV = "development"
    SCALERMAX_API_URL = "https://dev.api.scalermax.com"

[context.production.environment]
  SCALERMAX_API_URL = "https://api.scalermax.com"

[dev]
  command = "npm start"
  port = 8888
  targetPort = 3000
  publish = "dist"

[[context.development.headers]]
  for = "/*"
  [context.development.headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self' https://dev.api.scalermax.com; img-src 'self' data:; font-src 'self';"

[[context.production.headers]]
  for = "/*"
  [context.production.headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self' https://api.scalermax.com; img-src 'self' data:; font-src 'self';"

[[context.development.redirects]]
  from = "/api/*"
  to = "https://dev.api.scalermax.com/api/:splat"
  status = 200

[[context.production.redirects]]
  from = "/api/*"
  to = "https://api.scalermax.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200